---
- name: Run Ubuntu updates
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
